# Pipeline and library configurations - this file can be updated and is parsed by the pipeline
# it is meant to describe the configuration with which the pipeline was run so that
# it can be included easily in the reports.

# Note that this must be updated manually for now - a fully automatic configuration
# will be included with the workflow when all components are integrated.

[pipeline]
name                 = "mgp-cerebro"
version              = "0.7.0"
source               = "https://github.com/esteinig/cerebro"

# Configuration schema for traceable changes to parameters and other shenanigans
# this is the `nextflow.config` file used for the pipeline run

# Fields for the run configuration - can be filled in from database models

[pipeline.run]
run_id               = ""
started              = ""
completed            = ""

[pipeline.run.config]
name                 = "cerebro"
version              = "1.0"
file                 = ""

[pipeline.run.taxonomy]
name                = "ncbi"
date                = ""

# Databases constructed with CIPHER

[[pipeline.run.database]]
name                = ""
version             = ""
date                = ""
hash                = ""
cipher              = "cipher-v1.0"
description         = ""
citation            = ""

[[pipeline.run.database]]
name                = ""
version             = ""
date                = ""
hash                = ""
cipher              = "cipher-v1.0"
description         = ""
citation            = ""

[[pipeline.run.database]]
name                = ""
version             = ""
date                = ""
hash                = ""
cipher              = "cipher-v1.0"
description         = ""
citation            = ""

# Core dependencies Cerebro [please cite]

[[pipeline.dependencies]]
name                 = "cerebro"
version              = "0.7.0"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "taxonomy"
version              = "0.10.0"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "needletail"
version              = "0.4.1"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "niffler"
version              = "2.3.0"
source               = ""
citation             = ""


# Core pipeline dependencies [please cite]

[[pipeline.dependencies]]
name                 = "nextflow"
version              = "22.10.4"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "fastp"
version              = "0.23.2"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "scrubby"
version              = "0.3.0"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "minimap2"
version              = "1.3.5"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "strobealign"
version              = "0.8.0"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "vircov"
version              = "0.6.0"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "kraken2"
version              = "2.1.2"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "spades"
version              = "3.15.5"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "blast"
version              = "2.13.0"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "diamond"
version              = "2.1.4"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "mash"
version              = "2.3"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "ivar"
version              = "1.3.1"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "covtobed"
version              = "1.3.5"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "calib"
version              = "0.3.4"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "umi_tools"
version              = "1.3.5"
source               = ""
citation             = ""

[[pipeline.dependencies]]
name                 = "rasusa"
version              = "0.7.1"
source               = ""
citation             = ""


[[pipeline.dependencies]]
name                 = "cnvkit"
version              = "0.9.10"
source               = ""
citation             = ""


