[workspace]
members = [
    "cerebro/cerebro",
    "cerebro/lib/model",
    "cerebro/stack/report",
    "cerebro/stack/workflow",
    "cerebro/stack/server",
    "cerebro/stack/client",
    "cerebro/stack/watcher",
    "cerebro/stack/fs",
]
resolver = "2"